- name: create work dir
  file:
    path: "{{ workdir }}"
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ group }}"

- name: create log file
  file:
    path: "{{ log_file }}"
    state: touch
    mode: 0755
    owner: "{{ user }}"
    group: "{{ group }}"

- name: git pull from github
  git:
    repo: "{{ git_repo }}"
    dest: "{{ workdir }}"
    force: yes

- name: create binary excuted file
  environment:
    - PATH: $PATH:/usr/local/go/bin
    - GOPATH: "{{ go_path }}"
  shell: go build -o gowiki "{{ workdir }}/main.go"
  args:
    chdir: "{{ workdir }}"

- name: create config.json file
  template:
    src: config.json.j2
    dest: "{{ workdir }}/config.json"
    mode: 0644
    owner: "{{ user }}"
    group: "{{ group }}"

- name: play template module
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/wiki.conf
    mode: 0644
    owner: root
    group: root

- name: start supervisor
  supervisorctl:
    name: wiki
    state: restarted




