- name: create work dir
  file:
    path: "{{ workdir }}"
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ group }}"

- name: create wikilog file
  file:
    path: "{{ log_file }}"
    state: touch
    mode: 0644
    owner: "{{ user }}"
    group: "{{ group }}"

- name: git pull from github
  git:
    repo: "{{ git_repo }}"
    dest: "{{ workdir }}"
    force: yes

- name: Set GOPATH for all users and add to PATH
  template: src=go-path.sh.j2 dest=/etc/profile.d/go-path.sh mode=644

- name: create binary excuted file
  environment:
    GOPATH : "{{ go_path }}"
    PATH: "/usr/local/go/bin:{{ go_path }}/bin:{{ ansible_env.PATH }}"
  shell: go get . && go build -o gowiki "{{ workdir }}/main.go"
  args:
    chdir: "{{ workdir }}"

- name: create config.json file
  template:
    src: config.json.j2
    dest: "{{ workdir }}/config.json"
    mode: 0644
    owner: "{{ user }}"
    group: "{{ group }}"

- name: play template module
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/wiki.conf
    mode: 0644
    owner: root
    group: root

- name: start supervisor
  supervisorctl:
    name: wiki
    state: restarted




